GET http://localhost:3000/product/getproduct

###
POST http://localhost:3000/product/addproduct
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

immmmmmmmmm
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

hallo
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="pricing"

5.0
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="duration"

1.0
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="white.jpg"
Content-Type: image/jpeg

./white.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="pdf"; filename="candidaturePelerinage_1445500200544.pdf"
Content-Type: application/pdf

./candidaturePelerinage_1445500200544.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
DELETE http://localhost:3000/product/deleteproduct/654f73159c3e507fc15118eb

###
PUT http://localhost:3000/product/modifyproduct/654f73159c3e507fc15118eb
Content-Type: application/json

{
  "title": "iheb",
  "description": "hallo",
  "pricing": 5.0,
  "duration": 1.0,
  //"image": "image",
  //"pdf": "pdf"
}
